//SIGNUP ACTION TYPES
export const ON_SIGNUP_START = 'ON_SIGNUP_START'
export const ON_SIGNUP_SUCCESS = 'ON_SIGNUP_SUCCESS'
export const ON_SIGNUP_FAILED = 'ON_SIGNUP_FAILED'

//LOGIN ACTION TYPES
export const ON_LOGIN_START =   'ON_LOGIN_START'
export const ON_LOGIN_SUCCESS = 'ON_LOGIN_SUCCESS'
export const ON_LOGIN_FAILED =  'ON_LOGIN_FAILED'
